export type SampleProduct = {
  id: string;
  title: string;
  description: string;
  category: string;
  subcategory: string;
  price: number;
  sizes: string[];
  images: string[];
  status: "active" | "inactive";
  stock: number;
};

const placeholder = (slug: string, count = 3) =>
  Array.from({ length: count }, (_, index) => `https://picsum.photos/seed/${slug}-${index + 1}/800/1000`);

export const SAMPLE_PRODUCTS: SampleProduct[] = [
  {
    id: "men-tech-fleece-full-zip",
    title: "Nike Tech Fleece Full-Zip",
    description: "Streamlined double-knit fleece hoodie that traps warmth without the weight for all-season layering.",
    category: "men",
    subcategory: "hoodies",
    price: 134.95,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-tech-fleece-full-zip", 4),
    status: "active",
    stock: 18,
  },
  {
    id: "men-tech-joggers",
    title: "Nike Tech Joggers",
    description: "Tapered jogger built from signature Tech Fleece for structured comfort and a clean line.",
    category: "men",
    subcategory: "joggers",
    price: 99.95,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-tech-joggers"),
    status: "active",
    stock: 22,
  },
  {
    id: "men-essentials-hoodie",
    title: "Essentials Hoodie",
    description: "Heavyweight cotton-blend hoodie with tonal branding and a relaxed drape.",
    category: "men",
    subcategory: "hoodies",
    price: 89,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-essentials-hoodie", 4),
    status: "active",
    stock: 16,
  },
  {
    id: "men-essentials-tee",
    title: "Essentials Tee",
    description: "Signature oversized tee cut from premium jersey with subtle rubberized logo.",
    category: "men",
    subcategory: "tees",
    price: 39,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-essentials-tee"),
    status: "active",
    stock: 20,
  },
  {
    id: "men-jordan-4-black-cat",
    title: "Jordan 4 Black Cat",
    description: "All-black nubuck Jordan IV with mesh side panels and Air cushioning for everyday rotation.",
    category: "men",
    subcategory: "trainers",
    price: 229.95,
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
    images: placeholder("men-jordan-4-black-cat", 4),
    status: "active",
    stock: 12,
  },
  {
    id: "men-air-max-95-neon",
    title: "Air Max 95 Neon",
    description: "Iconic gradient suede overlays with visible heel and forefoot Air for cushioned spring.",
    category: "men",
    subcategory: "trainers",
    price: 174.95,
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
    images: placeholder("men-air-max-95-neon"),
    status: "active",
    stock: 14,
  },
  {
    id: "men-palm-angels-track-jacket",
    title: "Palm Angels Track Jacket",
    description: "Matte tricot jacket with contrast taping and a cropped stand collar silhouette.",
    category: "men",
    subcategory: "hoodies",
    price: 349.99,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-palm-angels-track-jacket", 4),
    status: "active",
    stock: 9,
  },
  {
    id: "men-stone-island-shadow-project-tee",
    title: "Stone Island Shadow Project Tee",
    description: "Garment-dyed tee with engineered ventilation panels and tonal badge.",
    category: "men",
    subcategory: "tees",
    price: 129,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-stone-island-shadow-project-tee"),
    status: "active",
    stock: 11,
  },
  {
    id: "men-acoldwall-panelled-hoodie",
    title: "A-COLD-WALL* Panelled Hoodie",
    description: "Technical nylon hoodie with asymmetrical zip pockets, reflective trims, and a structured hood.",
    category: "men",
    subcategory: "hoodies",
    price: 275,
    sizes: ["S", "M", "L", "XL"],
    images: placeholder("men-acoldwall-panelled-hoodie", 4),
    status: "active",
    stock: 7,
  },
  {
    id: "men-aime-leon-dore-rugby",
    title: "Aimé Leon Dore Rugby",
    description: "Heritage rugby tee crafted in heavy jersey with contrast collar and hidden placket.",
    category: "men",
    subcategory: "tees",
    price: 175,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("men-aime-leon-dore-rugby"),
    status: "active",
    stock: 10,
  },
  {
    id: "men-arcteryx-norvan-trainer",
    title: "Arc'teryx Norvan GTX Trainer",
    description: "Trail-ready trainer with GORE-TEX upper, Vibram outsole, and lightweight cushioning for wet conditions.",
    category: "men",
    subcategory: "trainers",
    price: 185,
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
    images: placeholder("men-arcteryx-norvan-trainer", 4),
    status: "active",
    stock: 10,
  },
  {
    id: "men-carhartt-wip-cargo-joggers",
    title: "Carhartt WIP Cargo Joggers",
    description: "Durable ripstop joggers with utilitarian pockets and a relaxed tapered fit.",
    category: "men",
    subcategory: "joggers",
    price: 105,
    sizes: ["28", "30", "32", "34", "36"],
    images: placeholder("men-carhartt-wip-cargo-joggers"),
    status: "active",
    stock: 19,
  },
  {
    id: "women-nike-pro-leggings",
    title: "Nike Pro Leggings",
    description: "Supportive Dri-FIT leggings with mesh ventilation panels for studio to street.",
    category: "women",
    subcategory: "leggings",
    price: 49.95,
    sizes: ["XS", "S", "M", "L", "XL"],
    images: placeholder("women-nike-pro-leggings"),
    status: "active",
    stock: 21,
  },
  {
    id: "women-new-balance-9060-rain-cloud",
    title: "New Balance 9060 Rain Cloud",
    description: "Stacked midsole runner with suede overlays and ABZORB cushioning in the Rain Cloud palette.",
    category: "women",
    subcategory: "trainers",
    price: 159.95,
    sizes: ["UK 4", "UK 5", "UK 6", "UK 7"],
    images: placeholder("women-new-balance-9060-rain-cloud", 4),
    status: "active",
    stock: 13,
  },
  {
    id: "women-zara-oversized-hoodie",
    title: "Zara Oversized Hoodie",
    description: "Soft brushed fleece hoodie with dropped shoulders and tonal drawcords.",
    category: "women",
    subcategory: "hoodies",
    price: 29.99,
    sizes: ["XS", "S", "M", "L"],
    images: placeholder("women-zara-oversized-hoodie"),
    status: "active",
    stock: 24,
  },
  {
    id: "women-essentials-crop-hoodie",
    title: "Fear of God Essentials Crop Hoodie",
    description: "Cropped silhouette in heavy fleece with exaggerated sleeves and tonal logo hit.",
    category: "women",
    subcategory: "hoodies",
    price: 110,
    sizes: ["XS", "S", "M", "L"],
    images: placeholder("women-essentials-crop-hoodie", 4),
    status: "active",
    stock: 15,
  },
  {
    id: "women-lululemon-scuba-hoodie",
    title: "Lululemon Scuba Oversized Hoodie",
    description: "Plush cotton-blend hoodie with roomy fit, half-zip neckline, and cozy Scuba fleece.",
    category: "women",
    subcategory: "hoodies",
    price: 118,
    sizes: ["2", "4", "6", "8", "10"],
    images: placeholder("women-lululemon-scuba-hoodie"),
    status: "active",
    stock: 18,
  },
  {
    id: "women-adidas-ultraboost-1-0",
    title: "Adidas Ultraboost 1.0",
    description: "Primeknit upper runner built on Boost cushioning with Stretchweb outsole.",
    category: "women",
    subcategory: "trainers",
    price: 165,
    sizes: ["UK 4", "UK 5", "UK 6", "UK 7"],
    images: placeholder("women-adidas-ultraboost-1-0", 4),
    status: "active",
    stock: 17,
  },
  {
    id: "women-alo-airbrush-legging",
    title: "Alo Yoga Airbrush Legging",
    description: "High-rise legging with smoothing Airbrush fabric and no side seams for studio wear.",
    category: "women",
    subcategory: "leggings",
    price: 89,
    sizes: ["XS", "S", "M", "L"],
    images: placeholder("women-alo-airbrush-legging"),
    status: "active",
    stock: 20,
  },
  {
    id: "women-reformation-studio-legging",
    title: "Reformation Studio Legging",
    description: "Eco-conscious compression legging with high-rise waistband and subtle sheen.",
    category: "women",
    subcategory: "leggings",
    price: 118,
    sizes: ["2", "4", "6", "8", "10"],
    images: placeholder("women-reformation-studio-legging"),
    status: "active",
    stock: 11,
  },
  {
    id: "kids-nike-air-max-270-gs",
    title: "Nike Air Max 270 GS",
    description: "Scaled-down Air Max 270 with oversized heel bubble and breathable mesh upper.",
    category: "kids",
    subcategory: "trainers",
    price: 109.95,
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6"],
    images: placeholder("kids-nike-air-max-270-gs"),
    status: "active",
    stock: 14,
  },
  {
    id: "kids-junior-essentials-hoodie",
    title: "Junior Essentials Hoodie",
    description: "Soft brushed jersey hoodie with front pouch pocket and rib trims for everyday wear.",
    category: "kids",
    subcategory: "hoodies",
    price: 65,
    sizes: ["7-8", "9-10", "11-12", "13-14"],
    images: placeholder("kids-junior-essentials-hoodie"),
    status: "active",
    stock: 19,
  },
  {
    id: "kids-adidas-superstar-j",
    title: "Adidas Superstar J",
    description: "Classic shell-toe Superstar scaled for juniors with leather upper and serrated stripes.",
    category: "kids",
    subcategory: "trainers",
    price: 79.95,
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6"],
    images: placeholder("kids-adidas-superstar-j"),
    status: "active",
    stock: 17,
  },
  {
    id: "kids-moncler-maia-puffer",
    title: "Moncler Maia Puffer",
    description: "Glossy lacquered nylon puffer with down fill and tonal hood for cold city commutes.",
    category: "kids",
    subcategory: "jackets",
    price: 249,
    sizes: ["6Y", "8Y", "10Y", "12Y"],
    images: placeholder("kids-moncler-maia-puffer", 4),
    status: "active",
    stock: 6,
  },
  {
    id: "kids-nike-club-fleece-hoodie",
    title: "Nike Club Fleece Hoodie",
    description: "Classic Club fleece hoodie with brushed interior, kangaroo pocket, and rib trims for playground comfort.",
    category: "kids",
    subcategory: "hoodies",
    price: 55,
    sizes: ["7-8", "9-10", "11-12", "13-14"],
    images: placeholder("kids-nike-club-fleece-hoodie"),
    status: "active",
    stock: 23,
  },
  {
    id: "kids-jordan-1-mid-gs",
    title: "Jordan 1 Mid GS",
    description: "Iconic AJ1 mid cut reworked for grade school sizing with cushioned foam midsole.",
    category: "kids",
    subcategory: "trainers",
    price: 114.95,
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6"],
    images: placeholder("kids-jordan-1-mid-gs"),
    status: "active",
    stock: 15,
  },
  {
    id: "accessories-north-face-borealis",
    title: "North Face Borealis Backpack",
    description: "Organization-rich 28L daypack with FlexVent suspension and padded laptop sleeve.",
    category: "accessories",
    subcategory: "bags",
    price: 94.95,
    sizes: ["OS"],
    images: placeholder("accessories-north-face-borealis"),
    status: "active",
    stock: 18,
  },
  {
    id: "accessories-new-era-9fifty",
    title: "New Era 9FIFTY Cap",
    description: "Structured snapback with raised embroidery and moisture-wicking sweatband.",
    category: "accessories",
    subcategory: "caps",
    price: 29.99,
    sizes: ["OS"],
    images: placeholder("accessories-new-era-9fifty"),
    status: "active",
    stock: 25,
  },
  {
    id: "accessories-stussy-canvas-tote",
    title: "Stüssy Canvas Tote",
    description: "Mid-weight cotton tote with stencil logo and reinforced handles for daily carry.",
    category: "accessories",
    subcategory: "bags",
    price: 59.95,
    sizes: ["OS"],
    images: placeholder("accessories-stussy-canvas-tote"),
    status: "active",
    stock: 20,
  },
  {
    id: "accessories-fjallraven-kanken-mini",
    title: "Fjällräven Kånken Mini",
    description: "Scaled Kånken backpack with Vinylon F fabric and convertible straps.",
    category: "accessories",
    subcategory: "bags",
    price: 84.95,
    sizes: ["OS"],
    images: placeholder("accessories-fjallraven-kanken-mini"),
    status: "active",
    stock: 14,
  },
  {
    id: "accessories-dior-sauvage-100ml",
    title: "Dior Sauvage 100ml",
    description: "Crisp bergamot and pepper opening balanced by ambroxan for lasting intensity.",
    category: "accessories",
    subcategory: "fragrance",
    price: 99,
    sizes: ["100ml"],
    images: placeholder("accessories-dior-sauvage-100ml"),
    status: "active",
    stock: 30,
  },
  {
    id: "accessories-creed-aventus-50ml",
    title: "Creed Aventus 50ml",
    description: "Pineapple and birch-led eau de parfum celebrating strength with refined projection.",
    category: "accessories",
    subcategory: "fragrance",
    price: 215,
    sizes: ["50ml"],
    images: placeholder("accessories-creed-aventus-50ml"),
    status: "active",
    stock: 9,
  },
];
